#This plugin was made by Fanouu. All Right Reserved
#Welcome to the config
#TIP: Type click = item right click & Type consume = item consumed
#default cookie
joint:
  id: "357:0"
  effects:
    #effect Name, effect duration (seconds), effect amplifier
    - "strength, 60, 1"
    - "nausea, 3, 5"
  type: click
  #cooldown is in seconds
  cooldown: 10
  cooldownMessage: "Please patiente {time} seconds"

cooked_chicken:
  id: "366:0"
  effects:
    #effect Name, effect duration (seconds), effect amplifier
    "strength, 120, 5"
  type: consume
  #cooldown is in seconds
  cooldown: 10
  cooldownMessage: "Please patiente {time} seconds"